import { useContext } from 'react'
import { Context } from '../../contexts/EventsProvider'
import EventTimeCard from '../EventTimeCard'
import {
  BlockContainer,
  HourContainer,
  InfoContainer,
  EventSheetContainer,
  TimeLapseContainer,
} from './styles'

export default function EventSheet() {
  const { state } = useContext(Context)

  return (
    <EventSheetContainer>
      <BlockContainer>
        <HourContainer>
          <p>01:00 </p>
        </HourContainer>
        <InfoContainer>
          <TimeLapseContainer>
            {state.events.map((event) => (
              <EventTimeCard key={event.id} event={event} />
            ))}
          </TimeLapseContainer>
          <div></div>
        </InfoContainer>
      </BlockContainer>
      <BlockContainer>
        <HourContainer>
          <p>02:00</p>
        </HourContainer>
        <InfoContainer>
          <div></div>
          <div></div>
        </InfoContainer>
      </BlockContainer>
      <BlockContainer>
        <HourContainer>
          <p>03:00</p>
        </HourContainer>
        <InfoContainer>
          <div></div>
          <div></div>
        </InfoContainer>
      </BlockContainer>
      <BlockContainer>
        <HourContainer>
          <p>04:00</p>
        </HourContainer>
        <InfoContainer>
          <div></div>
          <div></div>
        </InfoContainer>
      </BlockContainer>
      <BlockContainer>
        <HourContainer>
          <p>05:00</p>
        </HourContainer>
        <InfoContainer>
          <div></div>
          <div></div>
        </InfoContainer>
      </BlockContainer>
      <BlockContainer>
        <HourContainer>
          <p>06:00</p>
        </HourContainer>
        <InfoContainer>
          <div></div>
          <div></div>
        </InfoContainer>
      </BlockContainer>
      <BlockContainer>
        <HourContainer>
          <p>07:00</p>
        </HourContainer>
        <InfoContainer>
          <div></div>
          <div></div>
        </InfoContainer>
      </BlockContainer>
      <BlockContainer></BlockContainer>
      <BlockContainer>
        <HourContainer>
          <p>08:00</p>
        </HourContainer>
        <InfoContainer>
          <div></div>
          <div></div>
        </InfoContainer>
      </BlockContainer>
      <BlockContainer>
        <HourContainer>
          <p>09:00</p>
        </HourContainer>
        <InfoContainer>
          <div></div>
          <div></div>
        </InfoContainer>
      </BlockContainer>
      <BlockContainer>
        <HourContainer>
          <p>10:00</p>
        </HourContainer>
        <InfoContainer>
          <div></div>
          <div></div>
        </InfoContainer>
      </BlockContainer>
      <BlockContainer>
        <HourContainer>
          <p>11:00</p>
        </HourContainer>
        <InfoContainer>
          <div></div>
          <div></div>
        </InfoContainer>
      </BlockContainer>
      <BlockContainer>
        <HourContainer>
          <p>12:00</p>
        </HourContainer>
        <InfoContainer>
          <div></div>
          <div></div>
        </InfoContainer>
      </BlockContainer>
      <BlockContainer>
        <HourContainer>
          <p>13:00</p>
        </HourContainer>
        <InfoContainer>
          <div></div>
          <div></div>
        </InfoContainer>
      </BlockContainer>
      <BlockContainer>
        <HourContainer>
          <p>14:00</p>
        </HourContainer>
        <InfoContainer>
          <div></div>
          <div></div>
        </InfoContainer>
      </BlockContainer>
      <BlockContainer>
        <HourContainer>
          <p>15:00</p>
        </HourContainer>
        <InfoContainer>
          <div></div>
          <div></div>
        </InfoContainer>
      </BlockContainer>
      <BlockContainer>
        <HourContainer>
          <p>16:00</p>
        </HourContainer>
        <InfoContainer>
          <div></div>
          <div></div>
        </InfoContainer>
      </BlockContainer>
      <BlockContainer>
        <HourContainer>
          <p>17:00</p>
        </HourContainer>
        <InfoContainer>
          <div></div>
          <div></div>
        </InfoContainer>
      </BlockContainer>
      <BlockContainer>
        <HourContainer>
          <p>18:00</p>
        </HourContainer>
        <InfoContainer>
          <div></div>
          <div></div>
        </InfoContainer>
      </BlockContainer>
      <BlockContainer>
        <HourContainer>
          <p>19:00</p>
        </HourContainer>
        <InfoContainer>
          <div></div>
          <div></div>
        </InfoContainer>
      </BlockContainer>
      <BlockContainer>
        <HourContainer>
          <p>20:00</p>
        </HourContainer>
        <InfoContainer>
          <div></div>
          <div></div>
        </InfoContainer>
      </BlockContainer>
      <BlockContainer>
        <HourContainer>
          <p>21:00</p>
        </HourContainer>
        <InfoContainer>
          <div></div>
          <div></div>
        </InfoContainer>
      </BlockContainer>
      <BlockContainer>
        <HourContainer>
          <p>22:00</p>
        </HourContainer>
        <InfoContainer>
          <div></div>
          <div></div>
        </InfoContainer>
      </BlockContainer>
      <BlockContainer>
        <HourContainer>
          <p>23:00</p>
        </HourContainer>
        <InfoContainer>
          <div></div>
          <div></div>
        </InfoContainer>
      </BlockContainer>
    </EventSheetContainer>
  )
}
